new: Make sure the requested patchname would not create unnecessary problems
Using filenames containing e.g.,'/../' would cause problems. Avoid tripping
such problems by refusing to accept such patchnames.

Signed-off-by: Josef 'Jeff' Sipek <jsipek@cs.sunysb.edu>

diff --git a/guilt-new b/guilt-new
--- a/guilt-new
+++ b/guilt-new
@@ -55,6 +55,11 @@ if ! must_commit_first; then
 	die "Uncommited changes detected. Refresh first."
 fi
 
+if ! valid_patchname "$patch"; then
+	echo "Patchname is invalid." >&2
+	die "it cannot begin with '/', './' or '../', or contain /./ or /../"
+fi
+
 # create any directories as needed
 [ "`dirname $patch`" != "." ] && mkdir -p `dirname $GUILT_DIR/$branch/$patch`
 
