{fork,import}: check patchnames for colons
Since colons (':') are invalid characters in git ref names, guilt cannont
use any patch names that contain colons. Refuse to accept a colon in the
patch name.

Signed-off-by: Josef 'Jeff' Sipek <jeffpc@josefsipek.net>

diff --git a/guilt-import b/guilt-import
--- a/guilt-import
+++ b/guilt-import
@@ -34,6 +34,10 @@ if [ -e "$GUILT_DIR/$branch/$newname" ]; then
 	die "Already tracking a patch under that name."
 fi
 
+if ! valid_patchname "$newname"; then
+	die "The specified patch name contains invalid characters (:)."
+fi
+
 # create any directories as needed
 mkdir_dir=`dirname "$GUILT_DIR/$branch/$newname"`
 [ "$mkdir_dir" != "$GUILT_DIR/$branch" ] && mkdir -p "$mkdir_dir"
