regression: test that supplied test numbers are valid
Signed-off-by: Josef 'Jeff' Sipek <jeffpc@josefsipek.net>

diff --git a/regression/run-tests b/regression/run-tests
--- a/regression/run-tests
+++ b/regression/run-tests
@@ -27,7 +27,18 @@ DONE
 	exit 1
 }
 
-# usage: run_test <test name>
+# usage: check_test <test number>
+function check_test
+{
+	if [ ! -x "t-$1.sh" ]; then
+		echo "Test $1 does not exist or is not runnable" >&2
+		return 1
+	fi
+
+	return 0
+}
+
+# usage: run_test <test number>
 function run_test
 {
 	export REPODIR="/tmp/guilt.reg.$RANDOM"
@@ -40,12 +51,12 @@ function run_test
 
 	# run the test
 	cd $REPODIR > /dev/null
-	"$REG_DIR/$1" 2>&1 > "$LOGFILE"
+	"$REG_DIR/t-$1.sh" 2>&1 > "$LOGFILE"
 	ERR=$?
 	cd - > /dev/null
 
 	[ $? -ne 0 ] && test_failed
-	diff -u "`basename $1 .sh`.out" "$LOGFILE" || test_failed
+	diff -u "t-$1.out" "$LOGFILE" || test_failed
 
 	echo "done."
 
@@ -61,11 +72,15 @@ esac
 
 if [ $# -eq 0 ]; then
 	for t in t-*.sh ; do
-		run_test "$t"
+		run_test `echo "$t" | sed -e 's/^t-//' -e 's/\.sh$//'`
 	done
 else
 	for t in "$@" ; do
-		run_test "t-$t.sh"
+		check_test "$t"
+	done
+
+	for t in "$@" ; do
+		run_test "$t"
 	done
 fi
 
